'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import type {Patient} from '@/lib/demo';
type Entry={id:string;name:string;age:number;sex:string;conditions:string[];missing:number;shard:number};
export default function CohortBrowser({onOpen}:{onOpen:(p:Patient)=>void}){const [rows,setRows]=useState<Entry[]>([]),[query,setQuery]=useState(''),[page,setPage]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState('');
 useEffect(()=>{const c=new AbortController();fetch('/cohort/index.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Cohort could not be loaded.');return r.json();}).then(data=>setRows(data as Entry[])).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 const filtered=rows.filter(r=>`${r.id} ${r.name} ${r.sex} ${r.conditions.join(' ')}`.toLowerCase().includes(query.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/20));
 async function open(r:Entry){setLoading(r.id);setError('');try{let p:Patient|undefined;try{const saved=localStorage.getItem(`vitalckm-patient-${r.id}`);if(saved){const x=JSON.parse(saved);if(x.id===r.id&&Array.isArray(x.observations)&&Array.isArray(x.tasks)&&Array.isArray(x.conditions)&&Array.isArray(x.medications)&&Array.isArray(x.reports))p=x;}}catch{}if(!p){const res=await fetch(`/cohort/patients-${String(r.shard).padStart(3,'0')}.json`);if(!res.ok)throw Error('Patient shard could not be loaded.');const data:Patient[]=await res.json();p=data.find(p=>p.id===r.id);}if(!p)throw Error('Patient was not found.');onOpen(p);}catch(e){setError(String(e));}finally{setLoading('');}}
 return <section className="panel cohort-browser"><div className="panel-head"><div><div className="eyebrow">SYNTHETIC DEVELOPMENT COHORT</div><h2>Explore 5,000 CKM profiles</h2><p className="section-note">53 clinical/context attributes + ID · 3 historical visits · generated assumptions, not real patients or population prevalence.</p></div></div><Input aria-label="Search synthetic cohort" placeholder="Search ID, condition or sex…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/>{error&&<p role="alert">{error}</p>}{!rows.length&&!error&&<p>Loading cohort index…</p>}<Table><TableHeader><TableRow>{['Patient','Profile','Recorded conditions','Missing fields',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.slice(page*20,page*20+20).map(r=><TableRow key={r.id}><TableCell>{r.id}</TableCell><TableCell>{r.age} · {r.sex}</TableCell><TableCell>{r.conditions.join(', ')||'No listed conditions'}</TableCell><TableCell>{r.missing} lipid / ACR fields</TableCell><TableCell><Button variant="outline" disabled={!!loading} onClick={()=>open(r)}>{loading===r.id?'Loading…':'Open patient'}</Button></TableCell></TableRow>)}</TableBody></Table><div className="risk-actions"><span>{filtered.length.toLocaleString()} matches · page {page+1} of {pages}</span><Button variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>Next</Button></div></section>;
}
