'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {riskPercent,riskError,riskBand,comparisons,RISK_SOURCE,RISK_VERSION,type RiskProfile,type PatientAssessment} from '@/lib/risk';
import {profileFromPatient,inputSources,staleInputs,recordChanges,makeAssessment,patientHistory} from '@/lib/patient-workflow';
import {type Patient} from '@/lib/demo';
import type {RiskView} from './risk-workspace';
const pct=(n:number|null)=>n===null?'Unavailable':`${n.toFixed(1)}%`;
const pp=(n:number)=>`${n>0?'+':''}${n.toFixed(1)} pp`;
function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(x:string)=>void;options:string[]}){return <label className="risk-field"><span>{label}</span><Select value={value} onValueChange={v=>v!==null&&onChange(String(v))}><SelectTrigger aria-label={label}><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{options.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></label>}
function exportCsv(patientId:string,records:PatientAssessment[]){const rows=[['patient_id','saved_at','kind','risk_percent','model','age','sex','sbp_mmHg','tc_mg_dL','hdl_mg_dL'],...records.map(a=>[patientId,a.date,a.kind,riskPercent(a.profile)?.toFixed(4)??'',a.version,a.profile.age,a.profile.sex,a.profile.sbp,a.profile.tc,a.profile.hdl])];const csv=rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download=patientId+'-assessments.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function download(data:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function ConnectedRisk({patient,role,view,onView,onUpdate,onHealth}:{patient:Patient;role:string;view:RiskView;onView:(v:RiskView)=>void;onUpdate:(p:Patient)=>void;onHealth:()=>void}){
 const current=profileFromPatient(patient),fingerprint=JSON.stringify(current);
 const [draft,setDraft]=useState<RiskProfile>(current),[adjusted,setAdjusted]=useState<RiskProfile>(current),[scenarioBaseline,setScenarioBaseline]=useState<RiskProfile>(current),[scenarioSources,setScenarioSources]=useState(inputSources(patient)),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[message,setMessage]=useState(''),[error,setError]=useState(''),[deleting,setDeleting]=useState<string|null>(null),[staleConfirmed,setStaleConfirmed]=useState(false);
 useEffect(()=>{setDraft(profileFromPatient(patient));setAdjusted(profileFromPatient(patient));setScenarioBaseline(profileFromPatient(patient));setScenarioSources(inputSources(patient));setStaleConfirmed(false);setError('');},[fingerprint,patient.id]);
 const comparisonRisk=riskPercent(scenarioBaseline);
 const risk=riskPercent(current),preview=riskPercent(draft),scenario=riskPercent(adjusted),assessments=patientHistory(patient,'assessment'),scenarios=patientHistory(patient,'scenario'),sources=inputSources(patient),stale=staleInputs(patient),currentError=riskError(current);
 function saveActual(){try{if(stale.length&&!staleConfirmed)throw new Error('Review the older source measurements and acknowledge them before saving.');const p=recordChanges(patient,draft,date,role,()=>crypto.randomUUID());const fresh=profileFromPatient(p);const a=makeAssessment(p,fresh,'assessment',role,crypto.randomUUID(),new Date().toISOString());onUpdate({...p,riskHistory:[...(p.riskHistory||[]),a]});setError('');setMessage('New reported measurements saved to My Health. Assessment snapshot saved for this patient; review status remains visible.');}catch(e){setError(e instanceof Error?e.message:'Could not save assessment.');}}
 function saveScenario(){try{const a={...makeAssessment(patient,adjusted,'scenario',role,crypto.randomUUID(),new Date().toISOString()),baselineProfile:{...scenarioBaseline},sources:{...scenarioSources}};onUpdate({...patient,riskHistory:[...(patient.riskHistory||[]),a]});setMessage('Hypothetical scenario saved separately. My Health measurements have not changed.');setError('');}catch(e){setError(String(e));}}
 function discuss(a:PatientAssessment){if(patient.tasks.some(t=>t.assessmentId===a.id)){setMessage('This item is already linked to the care plan.');return;}onUpdate({...patient,tasks:[...patient.tasks,{id:crypto.randomUUID(),title:a.kind==='scenario'?'Discuss saved What-If scenario':'Review saved risk assessment',detail:`${a.kind==='scenario'?'Hypothetical, not an achieved measurement. ':''}Reference estimate ${pct(riskPercent(a.profile))}; saved ${new Date(a.date).toLocaleString()}. Discuss with the demo care team.`,due:new Date().toISOString().slice(0,10),done:false,assessmentId:a.id}]});setMessage('Discussion task added to My Care Plan. No clinical target or prescription was created.');}
 return <div className="risk-workspace">
 <section className="risk-context"><div><strong>{patient.name} · {patient.id}</strong><p>Connected to this patient’s My Health measurements and My Care Plan. Published Framingham reference results only. Experimental synthetic-model scores are confined to Research Lab.</p></div><Button variant="outline" onClick={onHealth}>Open My Health</Button></section>
 <nav className="risk-tabs" aria-label="Risk tools">{(['calculator','history','whatif'] as const).map((v,i)=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>onView(v)}>{['Risk Calculator','Risk Over Time','What-If'][i]}</button>)}</nav>
 {message&&<p className="notice" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 {view==='calculator'&&<>
 <div className="risk-result-grid"><section className="panel risk-score"><div className="eyebrow">CURRENT RECORDED METRICS · 10-YEAR GENERAL CVD</div><div className="risk-number">{pct(risk)}</div>{risk===null?<p>{currentError} Complete missing information below or in My Health. Nothing is filled with a default.</p>:<><span className={`risk-badge ${risk<10?'lower':risk<20?'intermediate':'higher'}`}>{riskBand(risk)} reference band</span><p>{current.age} years · {current.sex} · systolic {current.sbp.toFixed(0)} mmHg · total cholesterol {current.tc.toFixed(1)} mg/dL · HDL {current.hdl.toFixed(1)} mg/dL.</p><Button onClick={()=>{setAdjusted({...current});setScenarioBaseline({...current});setScenarioSources(inputSources(patient));onView('whatif');}}>Explore What-If</Button></>}<p>Equation for adults 30–74 without established CVD. Descriptive bands: &lt;10%, 10–&lt;20%, ≥20%; not prescribing thresholds. This is not a combined CKM score or a locally validated forecast.</p></section>
 <section className="panel"><h2>Measurements carried from My Health</h2><Table><TableHeader><TableRow>{['Input','Original value','Date / source','Status'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{['bp','tc','hdl'].map(k=><TableRow key={k}><TableCell>{{bp:'Systolic BP',tc:'Total cholesterol',hdl:'HDL'}[k]}</TableCell><TableCell>{sources[k]?`${sources[k].value} ${sources[k].unit}`:'Missing'}</TableCell><TableCell>{sources[k]?`${sources[k].date} · ${sources[k].source}`:'Add measurement'}</TableCell><TableCell>{sources[k]?(sources[k].reviewed?'Reviewed in demo':'Awaiting review'):'—'}</TableCell></TableRow>)}</TableBody></Table><p className="section-note">Lipid values in mmol/L are converted to mg/dL for this equation. Source values are retained. History and medication status come from the recorded baseline or an explicit update; missing history remains unknown.</p>{stale.length>0&&<p className="form-error">Older than 180 days: {stale.join(', ')}. This is a demo freshness flag, not a clinical testing interval.</p>}</section></div>
 <section className="panel"><h2>Add reported measurements and reassess</h2><p className="section-note">Use measured values here. Changes are saved as new observations, with date and source; earlier observations remain. For hypothetical values, use What-If. An unchanged value retains its original measurement date.</p><form onSubmit={e=>{e.preventDefault();saveActual();}}><div className="risk-input-grid">
 {([['age','Age at assessment',30,74],['sbp','Systolic BP (mmHg)',90,200],['tc','Total cholesterol (mg/dL)',100,400],['hdl','HDL cholesterol (mg/dL)',20,100]] as const).map(([k,label,min,max])=><label className="risk-field" key={k}><span>{label}</span><Input type="number" required min={min} max={max} step={k==='age'?1:.01} value={Number.isFinite(draft[k])?Math.round(draft[k]*100)/100:''} onChange={e=>setDraft({...draft,[k]:e.target.value===''?NaN:Number(e.target.value)})}/></label>)}
 <Pick label="Sex used by equation" value={draft.sex} options={['Female','Male']} onChange={v=>setDraft({...draft,sex:v as RiskProfile['sex']})}/>
 {([['treated','Currently taking BP medication'],['smoker','Current smoker'],['diabetes','Diabetes recorded'],['cvd','Established CVD / prior event']] as const).map(([k,label])=><Pick key={k} label={label} value={draft[k]===null?'Unknown':draft[k]?'Yes':'No'} options={['Unknown','No','Yes']} onChange={v=>setDraft({...draft,[k]:v==='Unknown'?null:v==='Yes'})}/>)}
 <label className="risk-field"><span>New measurement date</span><Input type="date" value={date} max={new Date().toISOString().slice(0,10)} required onChange={e=>setDate(e.target.value)}/></label>
 </div><p className="risk-preview"><strong>With entered values: {pct(preview)}</strong> · {preview===null?riskError(draft):'Preview only until saved. No clinical decision should be based on this demo.'}</p>{stale.length>0&&<label className="freshness-check"><Checkbox aria-label="Acknowledge older measurements" checked={staleConfirmed} onCheckedChange={v=>setStaleConfirmed(v===true)}/> I have reviewed the original dates; retained older values will remain visible in the snapshot.</label>}<div className="risk-actions"><Button type="submit" disabled={preview===null}>Save measurements & assessment</Button><Button type="button" variant="outline" onClick={()=>{setDraft(profileFromPatient(patient));setMessage('Current My Health values reloaded. Unsaved edits discarded.');}}>Reload My Health</Button><Button type="button" variant="outline" onClick={()=>window.print()}>Print / Save PDF</Button></div></form></section>
 </>}
 {view==='whatif'&&<>
 {risk===null?<section className="panel"><h2>Complete an eligible assessment first</h2><p>{currentError}</p><Button onClick={()=>onView('calculator')}>Open calculator</Button></section>:<><p>These hypothetical comparisons hold other inputs fixed. They do not estimate the benefit of a treatment, change your recorded measurements, or update a care-plan target.</p><div className="whatif-scores"><section className="panel"><div className="eyebrow">SCENARIO BASELINE</div><strong>{pct(comparisonRisk)}</strong></section><section className="panel adjusted-score" aria-live="polite"><div className="eyebrow">HYPOTHETICAL PROFILE</div><strong>{pct(scenario)}</strong><p>{scenario===null?riskError(adjusted):pp(scenario-(comparisonRisk??risk))}</p></section></div><section className="panel"><div className="panel-head"><h2>Explore different values</h2><Button variant="outline" onClick={()=>{setAdjusted(profileFromPatient(patient));setScenarioBaseline(profileFromPatient(patient));setScenarioSources(inputSources(patient));}}>Reset to My Health</Button></div><div className="risk-input-grid sliders"><Pick label="Current smoking in scenario" value={adjusted.smoker?'Smoker':'Not currently smoking'} options={['Smoker','Not currently smoking']} onChange={v=>setAdjusted({...adjusted,smoker:v==='Smoker'})}/>{([['sbp','Systolic BP','mmHg',90,200],['tc','Total cholesterol','mg/dL',100,400],['hdl','HDL cholesterol','mg/dL',20,100]] as const).map(([k,label,unit,min,max])=><div className="slider-field" key={k}><div><span>{label}</span><strong>{adjusted[k].toFixed(1)} {unit}</strong></div><Slider aria-label={label} min={min} max={max} step={1} value={[adjusted[k]]} onValueChange={v=>setAdjusted({...adjusted,[k]:Array.isArray(v)?v[0]:v})}/><small>Scenario baseline {scenarioBaseline[k].toFixed(1)} {unit}</small></div>)}</div><p className="section-note">Age, sex, diabetes and medication status stay fixed to the scenario baseline. Reopening a saved scenario retains its original baseline; Reset loads current My Health. BMI, kidney measures and other CKM attributes are available in My Health but are not inputs to this lipid-based equation.</p><div className="risk-actions"><Button disabled={scenario===null} onClick={saveScenario}>Save hypothetical scenario</Button></div></section><section className="panel"><h2>Single-input comparisons</h2><p>Each starts from the hypothetical profile above. Effects cannot be added together.</p>{comparisons(adjusted).map(x=><div className="impact-row" key={x.label}><span>{x.label}</span><div className="impact-track"><i style={{width:`${Math.min(100,Math.abs(x.delta)*10)}%`}}/></div><strong>{pp(x.delta)} → {pct(x.value)}</strong></div>)}</section></>}
 </>}
 {view==='history'&&<>
 <div className="risk-actions"><p>{assessments.length} recorded assessments · {scenarios.length} separate scenarios for {patient.id}</p><Button variant="outline" onClick={()=>download({patientId:patient.id,synthetic:true,assessments,scenarios},`${patient.id}-risk-history.json`)}>Export snapshots</Button><Button variant="outline" disabled={!assessments.length} onClick={()=>exportCsv(patient.id,assessments)}>Export assessment CSV</Button><Button variant="outline" onClick={()=>window.print()}>Print / Save PDF</Button></div>
 <section className="panel"><h2>Recorded-assessment trajectory</h2><p>Only saved assessments using {RISK_VERSION} appear here. Scenarios and experimental model scores are excluded.</p>{!assessments.length?<div className="risk-empty"><p>No saved assessments for this patient yet.</p><Button onClick={()=>onView('calculator')}>Create assessment</Button></div>:<svg viewBox="0 0 940 250" className="risk-chart" role="img" aria-label={assessments.map(a=>`${a.date}: ${pct(riskPercent(a.profile))}`).join('; ')}>{[0,25,50,75,100].map(v=><g key={v}><line x1="45" x2="925" y1={210-v*1.8} y2={210-v*1.8} stroke="#dbe2f0" strokeDasharray="4 4"/><text x="35" y={214-v*1.8} textAnchor="end">{v}%</text></g>)}<polyline fill="none" stroke="#025bcd" strokeWidth="2.5" points={assessments.map((a,i)=>`${assessments.length===1?485:50+i*860/(assessments.length-1)},${210-riskPercent(a.profile)!*1.8}`).join(' ')}/>{assessments.map((a,i)=><g key={a.id}><circle cx={assessments.length===1?485:50+i*860/(assessments.length-1)} cy={210-riskPercent(a.profile)!*1.8} r="4" fill="white" stroke="#025bcd" strokeWidth="2"><title>{new Date(a.date).toLocaleString()}: {pct(riskPercent(a.profile))}</title></circle>{(i===0||i===assessments.length-1)&&<text x={assessments.length===1?485:50+i*860/(assessments.length-1)} y="240" textAnchor={i===0?'start':'end'}>{new Date(a.date).toLocaleDateString()}</text>}</g>)}</svg>}</section>
 {(['assessment','scenario'] as const).map(kind=><section className="panel" key={kind}><h2>{kind==='assessment'?'Saved recorded assessments':'Saved hypothetical scenarios'}</h2><Table><TableHeader><TableRow>{['Saved','Reference risk','Status','Actions'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{patientHistory(patient,kind).slice().reverse().map(a=><TableRow key={a.id}><TableCell>{new Date(a.date).toLocaleString()}<small className="sample-tag">{a.savedBy} · {a.version}</small></TableCell><TableCell>{pct(riskPercent(a.profile))}</TableCell><TableCell>{kind==='scenario'?'Hypothetical':a.reviewedAt?'Reviewed in demo':'Awaiting review'}</TableCell><TableCell><div className="risk-actions"><Button variant="ghost" onClick={()=>{if(kind==='scenario'){setAdjusted({...a.profile});setScenarioBaseline(a.baselineProfile||current);setScenarioSources(a.sources);onView('whatif');}else{setDraft({...a.profile});onView('calculator');}setMessage('Saved snapshot loaded into editable fields. My Health remains unchanged until you explicitly save new measurements.');}}>Review inputs</Button><Button variant="ghost" onClick={()=>download(a,`${patient.id}-${a.id}.json`)}>Snapshot</Button><Button variant="ghost" onClick={()=>discuss(a)}>Add care-plan discussion</Button>{role==='clinician'&&kind==='assessment'&&!a.reviewedAt&&<Button variant="ghost" onClick={()=>{const ids=Object.values(a.sources).map(s=>s.id);onUpdate({...patient,observations:patient.observations.map(o=>ids.includes(o.id)?{...o,reviewed:true}:o),riskHistory:patient.riskHistory!.map(x=>x.id===a.id?{...x,reviewedAt:new Date().toISOString()}:x)});}}>Mark reviewed</Button>}<Button variant="ghost" onClick={()=>setDeleting(a.id)}>Delete</Button></div></TableCell></TableRow>)}</TableBody></Table>{!patientHistory(patient,kind).length&&<p className="section-note">No {kind==='scenario'?'scenarios':'assessments'} saved.</p>}</section>)}
 </>}
 <p className="risk-method"><a href={RISK_SOURCE} target="_blank" rel="noreferrer">Published equation and eligibility ↗</a> · No clinical accuracy established for this demo. Earlier standalone demo assessments are retained in browser storage but are not assigned to a patient automatically. Changes are stored in this browser only. Medication changes require clinical review.</p>
 <AlertDialog open={deleting!==null} onOpenChange={v=>!v&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this saved snapshot?</AlertDialogTitle><AlertDialogDescription>Only this patient’s selected snapshot and its linked discussion task will be removed. Recorded measurements remain.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep snapshot</AlertDialogCancel><AlertDialogAction onClick={()=>{onUpdate({...patient,riskHistory:patient.riskHistory?.filter(a=>a.id!==deleting),tasks:patient.tasks.filter(t=>t.assessmentId!==deleting)});setDeleting(null);}}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
