'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {type Governance,type SystemId,changeSystem,addIncident,closeIncident} from '@/lib/governance';
import type {Patient} from '@/lib/demo';
import {missing} from '@/lib/demo';
import './governance.css';
export default function GovernanceWorkspace({state,commit,patients,error}:{state:Governance;commit:(s:Governance)=>void;patients:Patient[];error:string}){
 const [actor,setActor]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState('Registry');
 const today=new Date().toISOString().slice(0,10);
 function run(fn:()=>Governance){try{commit(fn());setMessage('Demo record updated. No clinical approval or external notification was issued.');}catch(e){setMessage(String(e));}}
 function exportEvidence(){const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),scope:'Browser-local synthetic demonstration. Mutable records; identities not authenticated. Not a clinical approval.',...state},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='VitalCKM-governance-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="governance"><section className="panel"><h2>Governance & safety review</h2><p>Manage demonstration controls and document why decisions were made. Clinical deployment remains unavailable for every system.</p><p className="section-note">Browser-local simulation: names are self-declared, roles are not authenticated, records can be changed or cleared, and monitoring runs only while this app is open. No hospital-grade audit trail or background safety service is claimed.</p><div className="gov-summary"><span><b>{state.systems.filter(s=>s.paused).length}</b> paused systems</span><span><b>{state.incidents.filter(i=>i.status==='open').length}</b> open incidents</span><span><b>{state.systems.filter(s=>!s.due||s.due<today).length}</b> reviews missing / overdue</span><span><b>0</b> clinically approved systems</span></div><label>Your name for demo decisions<input value={actor} maxLength={100} onChange={e=>setActor(e.target.value)} placeholder="Enter reviewer name"/></label><Button variant="outline" onClick={exportEvidence}>Export governance record</Button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section><nav className="risk-tabs" aria-label="Governance sections">{['Registry','Incidents','Monitoring','Decision history'].map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='Registry'&&state.systems.map(s=><section className="panel" key={s.id}><div className="panel-head"><h2>{s.name}</h2><strong>{s.paused?'Paused in this browser':'Demo only'}</strong></div><p>{s.version} · {s.reason}</p><details><summary>Implementation / evidence identity</summary><pre>SHA-256: {s.fingerprint}</pre></details><p><strong>Clinical validation:</strong> Not established for VitalCKM patient care. {s.id==='research'?'Model metrics are conditional on the synthetic generator.':s.id==='reference'?'Published equation evidence does not establish local applicability.':'Priority thresholds require clinical ownership and validation.'}</p><p>{s.id==='reference'?<a href="https://www.framinghamheartstudy.org/fhs-for-researchers/fhs-risk-functions/cardiovascular-disease-10-year-risk/" target="_blank" rel="noreferrer">Published equation source</a>:s.id==='research'?<a href="/research/evaluation.json" target="_blank" rel="noreferrer">Synthetic evaluation report</a>:<span>Evidence gap: no approved local triage protocol or response-time commitment.</span>}</p><form key={JSON.stringify(s)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>changeSystem(state,s.id,{owner:String(f.get('owner')),reviewer:String(f.get('reviewer')),due:String(f.get('due')),reason:String(f.get('reason')),paused:f.get('paused')==='yes',reviewedAt:new Date().toISOString()},actor));}}><div className="gov-fields"><label>Accountable owner<input name="owner" defaultValue={s.owner} maxLength={100}/></label><label>Clinical reviewer<input name="reviewer" defaultValue={s.reviewer} maxLength={100}/></label><label>Next review date<input name="due" type="date" defaultValue={s.due}/></label><label>Demo availability<select name="paused" defaultValue={s.paused?'yes':'no'}><option value="no">Available for demo</option><option value="yes">Pause demo use</option></select></label></div><label>Decision rationale and evidence reviewed<textarea name="reason" required defaultValue={s.reason} maxLength={2000}/></label><Button type="submit">Record demo decision</Button></form><p className="section-note">{!s.owner?'Owner not assigned. ':''}{!s.due?'Review not scheduled.':s.due<today?'Review overdue.':'Next review: '+s.due} Changing the model, input schema, thresholds, population or workflow requires a new evidence review. This form cannot approve clinical use.</p></section>)}
 {tab==='Incidents'&&<><section className="panel"><h2>Report an incident</h2><p>High severity automatically pauses the affected demo workflow. No email or emergency response is sent.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>addIncident(state,{system:String(f.get('system')) as SystemId,severity:f.get('severity') as 'low'|'high',summary:String(f.get('summary')),owner:String(f.get('owner'))},actor));}}><div className="gov-fields"><label>Affected system<select name="system">{state.systems.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Severity<select name="severity"><option value="low">Low — review required</option><option value="high">High — pause affected workflow</option></select></label><label>Assigned incident owner<input name="owner" required maxLength={100}/></label></div><label>What happened (fictional information only)<textarea name="summary" required maxLength={2000}/></label><Button type="submit">Record incident</Button></form></section>{!state.incidents.length&&<section className="panel">No incidents recorded. This does not establish safety.</section>}{state.incidents.map(i=><section className="panel" key={i.id}><h3>{i.severity.toUpperCase()} · {i.status} · {i.system}</h3><p>{i.summary}</p><p>Owner: {i.owner} · {new Date(i.createdAt).toLocaleString()}</p>{i.status==='closed'?<p>Resolution: {i.resolution}. Resuming the system requires a separate decision.</p>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>closeIncident(state,i.id,String(f.get('resolution')),actor));}}><label>Investigation and corrective action<textarea name="resolution" required maxLength={2000}/></label><Button variant="outline" type="submit">Resolve incident</Button></form>}</section>)}</>}
 {tab==='Monitoring'&&<section className="panel"><h2>Current workspace checks</h2><p>{patients.length} loaded synthetic profiles; {patients.filter(p=>missing(p).length>0).length} have missing core measurements. This is a workspace sample, not the complete research cohort.</p><h3>Review queue</h3>{state.systems.map(s=><p key={s.id}>{s.name}: {!s.owner?'owner missing; ':''}{!s.due?'no review scheduled':s.due<today?'review overdue':'review due '+s.due}.</p>)}<h3>Drift and real-world performance</h3><p>Not measured. No live clinical feed, labelled outcomes or approved reference distribution is connected. Synthetic test AUC is not ongoing monitoring.</p><p>Before deployment, define the reference population, missingness and distribution checks, calibration and subgroup review, outcome delay, alert thresholds and response owners. Review model or workflow changes before release; retain previous versions for rollback.</p><h3>When a concern is identified</h3><p>Record the issue in Incidents, assign an owner, pause affected use when warranted, investigate and document corrective action, then explicitly review whether to resume. Follow the organisation’s clinical escalation process outside this demo.</p></section>}
 {tab==='Decision history'&&<section className="panel"><h2>Local event history</h2><p>Includes governance decisions and saved patient-workspace changes with before/after snapshots. Browser records are not immutable and do not capture external clinical actions.</p>{!state.events.length?<p>No events recorded yet.</p>:state.events.map(e=><details key={e.id}><summary>{new Date(e.at).toLocaleString()} · {e.action} · {e.actor}</summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}</section>}
 </div>;
}
