'use client';
import {useState} from 'react';
import {FileText,Download,ArrowUpRight} from 'lucide-react';
const docs=[
 {file:'VitalCKM_Business_Stakeholder_Brief',title:'Business stakeholder brief',audience:'BUSINESS & CLINICAL LEADERS',description:'Product value, evidence boundaries, dataset planning, training and evaluation, and staged rollout.'},
 {file:'VitalCKM_Clinical_Data_Review',title:'Clinical data review',audience:'CLINICAL & DATA TEAMS',description:'Review of the sample fields, recommended schema, clinical definitions, provenance and data quality.'},
 {file:'VitalCKM_Technical_Architecture_and_Scaling',title:'Technical architecture & scaling',audience:'ENGINEERING & INTEGRATION',description:'Production architecture, hospital integration, model lifecycle, security and capacity planning.'},
];
export default function Resources(){const [active,setActive]=useState(0);return <div className="resource-page"><section className="risk-context"><FileText size={22}/><p><strong>Project library.</strong> These documents preserve the original planning baseline. Since they were written, the demo has moved to Azure and added a published Framingham reference calculator. Their statements about disabled risk percentages describe the earlier release. A separate Research Lab now reports synthetic-only training and evaluation. No real-patient clinical accuracy or AUC has been established.</p></section><div className="resource-grid">{docs.map((d,i)=><section className={`panel resource-card ${active===i?'selected':''}`} key={d.file}><div className="eyebrow">{d.audience}</div><h2>{d.title}</h2><p>{d.description}</p><div className="risk-actions"><button className="text-link" onClick={()=>setActive(i)}>Read document <ArrowUpRight size={16}/></button><a className="text-link" href={`/resources/${d.file}.md`} download><Download size={16}/>Markdown</a></div></section>)}</div><section className="panel document-reader"><div className="panel-head"><h2>{docs[active].title}</h2><a className="text-link" href={`/resources/${docs[active].file}.html`} target="_blank" rel="noreferrer">Open full page / print <ArrowUpRight size={16}/></a></div><iframe key={active} title={docs[active].title} src={`/resources/${docs[active].file}.html`} sandbox="allow-same-origin"/></section></div>}
