'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Slider} from '@/components/ui/slider';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Download,ArrowRight,RotateCcw,Save,Info} from 'lucide-react';
import {EXAMPLE,RISK_VERSION,RISK_SOURCE,riskError,riskPercent,riskBand,comparisons,validAssessment,exampleHistory,type RiskProfile,type Assessment} from '@/lib/risk';
export type RiskView='calculator'|'history'|'whatif';
const KEY='vitalckm-risk-reference-v1';
const pct=(n:number|null)=>n===null?'—':`${n.toFixed(1)}%`;
const delta=(n:number)=>`${n>0?'+':''}${n.toFixed(1)} pp`;
function Pick({label,value,onChange,options}:{label:string;value:string;onChange:(x:string)=>void;options:string[]}){return <label className="risk-field"><span>{label}</span><Select value={value} onValueChange={v=>v!==null&&onChange(String(v))}><SelectTrigger aria-label={label}><SelectValue>{value}</SelectValue></SelectTrigger><SelectContent>{options.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></label>}
function saveFile(text:string,name:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function RiskWorkspace({view,onView}:{view:RiskView;onView:(v:RiskView)=>void}){
 const [profile,setProfile]=useState<RiskProfile>({...EXAMPLE}),[draft,setDraft]=useState<RiskProfile>({...EXAMPLE}),[adjusted,setAdjusted]=useState<RiskProfile>({...EXAMPLE}),[history,setHistory]=useState<Assessment[]>([]),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[deleting,setDeleting]=useState<string|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const d=JSON.parse(raw);if(Array.isArray(d.history)&&d.history.every(validAssessment)&&!riskError(d.profile)){setHistory(d.history);setProfile(d.profile);setDraft(d.profile);setAdjusted(d.profile);}else setMessage('Saved risk data could not be read. The fictional example has been restored.');}}catch{setMessage('Browser storage is unavailable. This session still works.');}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(KEY,JSON.stringify({profile,history}));}catch{setMessage('Changes are available for this session only.');}},[profile,history,ready]);
 const result=riskPercent(profile),scenario=riskPercent(adjusted),items=comparisons(profile),changes=comparisons(adjusted);
 function calculate(){const e=riskError(draft);if(e){setError(e);return;}setProfile({...draft});setAdjusted({...draft});setError('');setMessage('Reference estimate updated. Save it to include it in your history.');}
 function load(a:Assessment){setProfile({...a.profile});setDraft({...a.profile});setAdjusted({...a.profile});setError('');setMessage('Saved input snapshot loaded. Its original assessment remains unchanged.');onView('calculator');}
 function reset(){setAdjusted({...profile});setMessage('What-If values reset to the current assessment.');}
 const sorted=[...history].sort((a,b)=>a.date.localeCompare(b.date));const last=sorted.at(-1),prior=sorted.at(-2);
 return <div className="risk-workspace">
  <div className="risk-context"><Info size={18}/><p><strong>Fictional assessment workspace.</strong> Separate from the patient directory. Framingham 2008 general CVD reference equation · ages 30–74 without established CVD. Not a trained VitalCKM AI model or a validated Vietnamese risk estimate.</p></div>
  <nav className="risk-tabs" aria-label="Risk tools">{(['calculator','history','whatif'] as const).map((v,i)=><button key={v} aria-current={view===v?'page':undefined} onClick={()=>onView(v)}>{['Risk Calculator','Risk Over Time','What-If'][i]}</button>)}</nav>
  {message&&<p className="notice" role="status">{message}</p>}
  {view==='calculator'&&<>
   <details className="panel assessment-form" open><summary>Edit fictional assessment</summary><form onSubmit={e=>{e.preventDefault();calculate();}}><div className="risk-input-grid">
    {([['age','Age (years)',30,74],['sbp','Systolic BP (mmHg)',90,200],['tc','Total cholesterol (mg/dL)',100,400],['hdl','HDL cholesterol (mg/dL)',20,100]] as const).map(([k,label,min,max])=><label className="risk-field" key={k}><span>{label}</span><Input required aria-label={label} type="number" min={min} max={max} step="1" value={Number.isNaN(draft[k])?'':draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value===''?NaN:Number(e.target.value)})}/></label>)}
    <Pick label="Sex used by equation" value={draft.sex} options={['Female','Male']} onChange={sex=>setDraft({...draft,sex:sex as RiskProfile['sex']})}/>
    {([['treated','Taking BP medication'],['smoker','Current smoker'],['diabetes','Diabetes'],['cvd','Established CVD / prior event'],['acute','Current acute illness']] as const).map(([k,label])=><Pick key={k} label={label} value={draft[k]?'Yes':'No'} options={['No','Yes']} onChange={v=>setDraft({...draft,[k]:v==='Yes'})}/>)}
   </div>{error&&<p role="alert" className="form-error">{error} The result below remains the last completed assessment.</p>}<div className="risk-actions"><Button type="submit">Calculate reference risk</Button><Button variant="outline" type="button" onClick={()=>{setDraft({...EXAMPLE});setError('');setMessage('Example inputs loaded. Calculate to update the result.');}}>Load fictional example</Button></div></form></details>
   <div className="risk-result-grid"><section className="panel risk-score"><div className="eyebrow">10-YEAR GENERAL CVD · REFERENCE ESTIMATE</div><div className="risk-number">{pct(result)}</div><p className="result-snapshot">Completed inputs: {profile.sex}, age {profile.age} · SBP {profile.sbp} · total cholesterol {profile.tc} · HDL {profile.hdl} · {profile.smoker?'current smoker':'not currently smoking'} · BP medication {profile.treated?'yes':'no'} · diabetes {profile.diabetes?'yes':'no'}. Edit and calculate above to update.</p>{result!==null&&<><span className={`risk-badge ${result<10?'lower':result<20?'intermediate':'higher'}`}>{riskBand(result)} reference band</span><div className="risk-scale" aria-hidden="true"><span style={{left:`${Math.min(100,result)}%`}}/></div><p className="risk-meaning">The equation returns approximately {result.toFixed(0)} events per 100 people over 10 years for this fictional profile. This is not a locally calibrated forecast.</p></>}<p>The outcome includes several cardiovascular conditions, including heart failure; it is not the same as an ASCVD-only estimate.</p><div className="risk-actions"><Button disabled={!ready||result===null} onClick={()=>{setHistory(h=>[...h,{id:crypto.randomUUID(),date:new Date().toISOString(),profile:{...profile},version:RISK_VERSION}]);setMessage('Assessment saved in this browser. Open Risk Over Time to review it.');}}><Save size={16}/>Save assessment</Button><Button variant="outline" onClick={()=>window.print()}>Print / Save PDF</Button></div><details><summary>How to read the bands</summary><p>Display bands: below 10%, 10% to below 20%, and 20% or above. These are descriptive bands for this demo, not prescribing thresholds. Age, medical history and local guidance matter.</p></details></section>
   <div className="risk-stack"><section className="panel"><h2>Explore what influences the estimate</h2><p>One input changed at a time; all others held fixed. These comparisons are not SHAP explanations or causal effects.</p>{items.map(x=><div className="impact-row" key={x.label}><span>{x.label}</span><div className="impact-track"><i style={{width:`${Math.min(100,Math.abs(x.delta)/Math.max(1,...items.map(t=>Math.abs(t.delta)))*100)}%`}}/></div><strong>{delta(x.delta)}</strong></div>)}</section><section className="panel"><h2>If an input were different…</h2><p>Explore hypothetical profiles, without changing the saved assessment.</p><div className="scenario-cards">{items.map(x=><button key={x.label} onClick={()=>{setAdjusted({...profile,...x.patch});onView('whatif');}}><span>{x.label}</span><strong>{pct(x.value)} <small>{delta(x.delta)}</small></strong><ArrowRight size={17}/></button>)}</div></section></div></div>
  </>}
  {view==='history'&&<>
   <div className="risk-actions"><p>{history.length} fictional assessments saved in this browser</p><Button variant="outline" onClick={()=>window.print()}>Print / Save PDF</Button><Button variant="outline" disabled={!history.length} onClick={()=>{const fields=['date','risk_percent','model','sex','age','sbp_mmHg','total_cholesterol_mg_dL','hdl_mg_dL','bp_treated','current_smoker','diabetes'];saveFile([fields.join(','),...sorted.map(a=>[a.date,riskPercent(a.profile)!.toFixed(4),a.version,a.profile.sex,a.profile.age,a.profile.sbp,a.profile.tc,a.profile.hdl,a.profile.treated,a.profile.smoker,a.profile.diabetes].join(','))].join('\n'),'VitalCKM-fictional-risk-history.csv','text/csv');}}><Download size={16}/>Export CSV</Button></div>
   {!last?<section className="panel risk-empty"><h2>Your assessment history starts here</h2><p>Save a calculator result, or load three clearly fictional examples to explore the chart.</p><Button onClick={()=>{setHistory(exampleHistory());setMessage('Three fictional sample assessments loaded. They are not patient outcomes.');}}>Load example history</Button><Button variant="outline" onClick={()=>onView('calculator')}>Open calculator</Button></section>:<>
   <div className="risk-stat-grid">{[['Risk',pct(riskPercent(last.profile)),prior?delta(riskPercent(last.profile)!-riskPercent(prior.profile)!):'First assessment'],['Systolic BP',`${last.profile.sbp} mmHg`,prior?`${last.profile.sbp-prior.profile.sbp} mmHg from previous`:''],['Total cholesterol',`${last.profile.tc} mg/dL`,prior?`${last.profile.tc-prior.profile.tc} mg/dL from previous`:''],['BMI (context)',last.profile.bmi.toFixed(1),'Not used in lipid equation']].map(([label,value,note])=><section className="panel" key={label}><div className="eyebrow">{label}</div><strong>{value}</strong><p>{note}</p></section>)}</div>
   <section className="panel"><h2>Risk trajectory</h2><p>Saved estimates, not observed outcomes. Changes can reflect different inputs and are not proof of treatment effect.</p><svg viewBox="0 0 940 250" className="risk-chart" role="img" aria-label={`Fictional risk history: ${sorted.map(a=>`${new Date(a.date).toLocaleDateString('en-GB')}: ${pct(riskPercent(a.profile))}`).join('; ')}`}>
    {[0,25,50,75,100].map(v=><g key={v}><line x1="45" x2="925" y1={210-v*1.8} y2={210-v*1.8} stroke="#dbe2f0" strokeDasharray="4 4"/><text x="35" y={214-v*1.8} textAnchor="end">{v}%</text></g>)}
    <polyline fill="none" stroke="#025bcd" strokeWidth="2.5" points={sorted.map((a,i)=>`${sorted.length===1?485:50+i*860/(sorted.length-1)},${210-riskPercent(a.profile)!*1.8}`).join(' ')}/>
    {sorted.map((a,i)=><g key={a.id}><circle cx={sorted.length===1?485:50+i*860/(sorted.length-1)} cy={210-riskPercent(a.profile)!*1.8} r="4" fill="white" stroke="#025bcd" strokeWidth="2"><title>{new Date(a.date).toLocaleString()}: {pct(riskPercent(a.profile))}</title></circle>{(i===0||i===sorted.length-1)&&<text x={sorted.length===1?485:50+i*860/(sorted.length-1)} y="240" textAnchor={i===0?'start':'end'}>{new Date(a.date).toLocaleDateString('en-GB')}</text>}</g>)}
   </svg></section><section className="panel"><Table><TableHeader><TableRow>{['Date','Risk','Band','SBP','Total chol.','HDL','Actions'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{[...sorted].reverse().map(a=><TableRow key={a.id}><TableCell>{new Date(a.date).toLocaleString()}{a.id.startsWith('example-')&&<small className="sample-tag">Fictional example</small>}</TableCell><TableCell>{pct(riskPercent(a.profile))}</TableCell><TableCell>{riskBand(riskPercent(a.profile)!)}</TableCell><TableCell>{a.profile.sbp}</TableCell><TableCell>{a.profile.tc}</TableCell><TableCell>{a.profile.hdl}</TableCell><TableCell><Button variant="ghost" onClick={()=>load(a)}>Recalculate</Button><Button variant="ghost" onClick={()=>setDeleting(a.id)}>Delete</Button></TableCell></TableRow>)}</TableBody></Table><p className="section-note">Blood pressure in mmHg; cholesterol in mg/dL. All snapshots use {RISK_VERSION}.</p></section></>}
  </>}
  {view==='whatif'&&<>
   <p className="risk-lead">Adjust a fictional profile and explore how the reference equation responds. This is a sensitivity analysis, not a prediction of the benefit of changing treatment or lifestyle.</p>
   <div className="whatif-scores"><section className="panel"><div className="eyebrow">YOUR CURRENT ASSESSMENT</div><strong>{pct(result)}</strong></section><section className="panel adjusted-score" aria-live="polite"><div className="eyebrow">WITH YOUR ADJUSTMENTS</div><strong>{pct(scenario)}</strong><p>{scenario!==null&&result!==null?`${delta(scenario-result)} compared with baseline`:riskError(adjusted)}</p></section></div>
   <section className="panel"><div className="panel-head"><h2>Adjust health factors</h2><Button variant="outline" onClick={reset}><RotateCcw size={16}/>Reset to baseline</Button></div><div className="risk-input-grid sliders">
    <Pick label="Current smoking status" value={adjusted.smoker?'Smoker':'Not currently smoking'} options={['Smoker','Not currently smoking']} onChange={v=>setAdjusted({...adjusted,smoker:v==='Smoker'})}/>
    {([['sbp','Systolic blood pressure','mmHg',90,200,1],['tc','Total cholesterol','mg/dL',100,400,1],['hdl','HDL cholesterol','mg/dL',20,100,1],['bmi','Body mass index','kg/m²',15,60,.1],['ldl','LDL cholesterol','mg/dL',20,350,1],['glucose','Blood glucose','mg/dL',40,400,1],['heartRate','Heart rate','bpm',40,180,1]] as const).map(([k,label,unit,min,max,step])=><div className="slider-field" key={k}><div><span id={`label-${k}`}>{label}</span><strong>{adjusted[k]} {unit}</strong></div><Slider aria-label={label} value={[adjusted[k]]} min={min} max={max} step={step} onValueChange={v=>setAdjusted({...adjusted,[k]:Array.isArray(v)?v[0]:v})}/><small>{['bmi','ldl','glucose','heartRate'].includes(k)?'Context only · not used by this equation':`Baseline ${profile[k]} ${unit}`}</small></div>)}
   </div><p className="section-note">Smoking is a yes/no predictor, not cigarettes per day. BMI, LDL, glucose and heart rate are shown for context and do not change this lipid-based score. A zero change does not mean a factor has no health importance. BP treatment and diabetes status stay fixed.</p></section>
   <section className="panel"><h2>Single-input comparisons</h2><p>Each comparison starts from your current adjustments. Differences cannot be added together.</p>{changes.map(x=><div className="impact-row" key={x.label}><span>{x.label}</span><div className="impact-track"><i style={{width:`${Math.min(100,Math.abs(x.delta)/Math.max(1,...changes.map(t=>Math.abs(t.delta)))*100)}%`}}/></div><strong>{delta(x.delta)} → {pct(x.value)}</strong></div>)}</section>
  </>}
  <p className="risk-method"><a href={RISK_SOURCE} target="_blank" rel="noreferrer">Published equation and eligibility ↗</a> · {RISK_VERSION}. No clinical accuracy or AUC has been established for this demo. Do not change medication based on this tool.</p>
  <AlertDialog open={deleting!==null} onOpenChange={v=>!v&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this saved assessment?</AlertDialogTitle><AlertDialogDescription>This removes one fictional snapshot from this browser. The current calculator inputs remain available.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep assessment</AlertDialogCancel><AlertDialogAction onClick={()=>{setHistory(h=>h.filter(a=>a.id!==deleting));setDeleting(null);}}>Delete assessment</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
