export type Metric='bp'|'egfr'|'hba1c'|'uacr'|'weight'|'creatinine';
export type Observation={id:string;kind:Metric;value:number;second?:number;unit:string;date:string;source:'Clinic'|'Laboratory'|'Home';reviewed:boolean};
export type Medication={id:string;name:string;dose:string;className:string;since:string;adherence:'Not reported'|'As prescribed'|'Sometimes missed'|'Not taking'};
export type Task={id:string;title:string;detail:string;due:string;done:boolean};
export type Report={id:string;text:string;date:string;reviewed:boolean};
export type Patient={id:string;name:string;age:number;sex:'Female'|'Male';height:number;scenario:string;conditions:string[];chronicity:string;acute:boolean;smoking:string;observations:Observation[];medications:Medication[];tasks:Task[];reports:Report[]};
export const metricInfo:Record<Metric,{label:string;unit:string;min:number;max:number;step:number}>={bp:{label:'Blood pressure',unit:'mmHg',min:40,max:300,step:1},egfr:{label:'Laboratory eGFR',unit:'mL/min/1.73 m²',min:1,max:250,step:.1},hba1c:{label:'HbA1c',unit:'%',min:2,max:25,step:.1},uacr:{label:'Urine ACR',unit:'mg/g',min:0,max:20000,step:.1},weight:{label:'Weight',unit:'kg',min:20,max:400,step:.1},creatinine:{label:'Serum creatinine',unit:'µmol/L',min:10,max:2500,step:.1}};
export function latest(p:Patient,kind:Metric){return p.observations.filter(o=>o.kind===kind).sort((a,b)=>b.date.localeCompare(a.date)||p.observations.indexOf(b)-p.observations.indexOf(a))[0]}
export function missing(p:Patient){return (['bp','egfr','hba1c','uacr'] as Metric[]).filter(k=>!latest(p,k))}
export function pending(p:Patient){return p.observations.filter(o=>!o.reviewed).length+p.reports.filter(r=>!r.reviewed).length}
export function dateLabel(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}
const dates=['2026-03-20','2026-04-22','2026-05-20','2026-06-24','2026-07-22','2026-08-28'];
const scenarios=[
 {age:58,sex:'Female',height:160,weight:66.8,bp:132,dia:82,g:58,a:85,h:6.8,cr:98,conditions:['Type 2 diabetes','Hypertension','Documented CKD'],label:'Diabetes and CKD follow-up',chronicity:'Documented in the synthetic history since March 2026',acute:false},
 {age:46,sex:'Male',height:173,weight:79,bp:138,dia:86,g:87,a:null,h:5.9,cr:94,conditions:['Hypertension'],label:'Urine ACR not yet measured',chronicity:'Not established',acute:false},
 {age:68,sex:'Female',height:157,weight:65,bp:126,dia:76,g:44,a:180,h:6.5,cr:130,conditions:['Heart failure','Type 2 diabetes','Documented CKD'],label:'Heart failure and kidney follow-up',chronicity:'Documented in the synthetic history since March 2026',acute:false},
 {age:35,sex:'Female',height:163,weight:71,bp:118,dia:74,g:103,a:12,h:5.8,cr:66,conditions:['History of gestational diabetes'],label:'Metabolic health follow-up',chronicity:'Not established',acute:false},
 {age:64,sex:'Male',height:169,weight:73,bp:128,dia:78,g:71,a:22,h:5.7,cr:102,conditions:['Coronary artery disease','Prior MI','Hypertension'],label:'Existing cardiovascular disease',chronicity:'Not established',acute:false},
 {age:52,sex:'Male',height:175,weight:88,bp:144,dia:88,g:38,a:null,h:6.1,cr:181,conditions:['Acute kidney injury under review','Hypertension'],label:'Acute kidney change; do not infer CKD',chronicity:'Unknown; acute illness at the latest visit',acute:true},
 {age:72,sex:'Female',height:155,weight:61,bp:134,dia:78,g:29,a:410,h:7.1,cr:160,conditions:['Documented CKD','Type 2 diabetes'],label:'Advanced kidney disease follow-up',chronicity:'Documented in the synthetic history since March 2026',acute:false},
 {age:41,sex:'Male',height:176,weight:81,bp:122,dia:78,g:98,a:8,h:null,cr:86,conditions:[],label:'Baseline screening; HbA1c missing',chronicity:'Not established',acute:false}
] as const;
export function seedPatients():Patient[]{return scenarios.map((s,i)=>{
 const observations:Observation[]=[];
 dates.forEach((date,j)=>{const delta=5-j;const values:Partial<Record<Metric,number>>={bp:s.bp+delta*2,weight:Math.round((s.weight+delta*.4)*10)/10,creatinine:s.acute&&j<5?92:s.cr,egfr:s.acute&&j<5?88:s.g+delta};if(s.h!==null)values.hba1c=Math.round((s.h+delta*.06)*10)/10;if(s.a!==null)values.uacr=s.a+delta*2;Object.entries(values).forEach(([kind,value])=>observations.push({id:`p${i}-${kind}-${j}`,kind:kind as Metric,value:value!,...(kind==='bp'?{second:s.dia+Math.floor(delta/2)}:{}),unit:metricInfo[kind as Metric].unit,date,source:kind==='bp'||kind==='weight'?'Clinic':'Laboratory',reviewed:true}))});
 const medications:Medication[]=[];
 if(s.conditions.some(c=>c.includes('diabetes')))medications.push({id:`m${i}-1`,name:'Empagliflozin',dose:'10 mg · oral · once daily',className:'SGLT2 inhibitor',since:'2026-03-20',adherence:'Not reported'});
 if(s.conditions.some(c=>c.includes('Hypertension')))medications.push({id:`m${i}-2`,name:'Losartan',dose:'50 mg · oral · once daily',className:'Angiotensin receptor blocker',since:'2026-03-20',adherence:'Not reported'});
 if(i===4)medications.push({id:`m${i}-3`,name:'Atorvastatin',dose:'40 mg · oral · once daily',className:'Statin',since:'2026-03-20',adherence:'Not reported'});
 return {id:`CKM-${String(i+1).padStart(3,'0')}`,name:`Demo patient ${String(i+1).padStart(2,'0')}`,age:s.age,sex:s.sex,height:s.height,scenario:s.label,conditions:[...s.conditions],chronicity:s.chronicity,acute:s.acute,smoking:i===4?'Former':'Never',observations,medications,tasks:[{id:`t${i}-1`,title:'Review recent measurements',detail:'Discuss the recorded blood pressure and laboratory results at the next visit.',due:'2026-09-14',done:false},{id:`t${i}-2`,title:medications.length?'Medication check-in':'Prepare for the next visit',detail:medications.length?'Confirm the current list and report any difficulties taking medicines.':'Write down questions to discuss with the care team.',due:'2026-09-14',done:false}],reports:[]};
})}
export function validateObservation(kind:Metric,value:number,second:number|undefined,date:string){const m=metricInfo[kind];if(!m||!Number.isFinite(value)||value<m.min||value>m.max)return 'Enter a value within the demo input bounds.';if(kind==='bp'&&(!Number.isFinite(second)||second!<20||second!>=value))return 'Diastolic pressure must be at least 20 and below systolic pressure.';const parsed=new Date(date+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(+parsed)||parsed.toISOString().slice(0,10)!==date||date>new Date().toISOString().slice(0,10))return 'Choose a valid measurement date that is not in the future.';return null}
